### ISSUE TITLE
Value is not able to set in hmpoText

### ISSUE THREAD

**Issue by santhuisland** [UKHomeOffice/passports-components#45]
HI,

i am trying to set value in html but not working
{{ hmpoText(ctx, { id: "browseEntryNumber" , classes: "govuk-input--width-10" ,value:"19-0123456", attributes:{ readonly : true}   } )
   }}

**i suspect there is some problem in** 
 hmpoGetValue(ctx, params) {
        let errorValue = ctx('errorValues.' + params.id);
        return errorValue !== undefined ? errorValue :ctx('values.' + params.id);
    }

**if i use this directly it works**
  {{ govukInput({ label: { text: "Event name" },id: "browseEntryCreatedBy1",name: "browseEntryCreatedBy1" ,value:"testing" }) }}

Thanks
Santhosh

**Comment by HughePaul** [comment]
If its a field that doesn't need to feed off the form-wizard, then you should use the govuk component instead. the hmpo components are designed to get their values from the form wizard sessionModel
